dof:
    6
ctrl_matrix:
    [[1,0,0,  0,   0,   0],
     [0,1,0,  0,   0,   0],
     [0,0,1,  0,   0,   0],
     [0,0,0,0.2,   0,   0],
     [0,0,0,  0, 0.2,   0],
     [0,0,0,  0,  0,  0.2]]
sigma:
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
    # [0.02, 0.02, 0., 0., 0., 0.01, 0.01, 0.01, 0., 0., 0., 0.005]